version: "3"

services:
  restic:
    build: .
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ=America/Sao_Paulo
      - RESTIC_REPOSITORY=/root/repo
      - RESTIC_PASSWORD
    ports:
      - "8888:8888"
    volumes:
      - cache:/root/.cache/restic
      - /Volumes/backup0/BackupRestic:/root/repo

volumes:
  cache: